<?php
/**
 * Change log :
 * - %AUTOGENERATEDDATE% : Log file auto generated
 */


/**
 * Uncomment and change these global settings if you want !
 */
//define( 'TITLE'                    , 'Pimp my Log' );
//define( 'NAV_TITLE'                , '' );
//define( 'FOOTER'                   , '&copy; <a href="http://www.potsky.com" target="doc">Potsky</a> 2007-' . @date('Y') . ' - <a href="http://pimpmylog.com" target="doc">Pimp my Log</a>');
//define( 'LOGS_MAX'                 , 10 );
//define( 'LOGS_REFRESH'             , 7 );
//define( 'NOTIFICATION'             , true );
//define( 'NOTIFICATION_TITLE'       , 'New logs [%f]' );
//define( 'GOOGLE_ANALYTICS'         , 'UA-XXXXX-X' );
//define( 'PULL_TO_REFRESH'          , true );
//define( 'GEOIP_URL'                , 'http://www.geoiptool.com/en/?IP=%p' );
//define( 'CHECK_UPGRADE'            , true );
//define( 'MAX_SEARCH_LOG_TIME'      , 3 );
//define( 'USER_TIME_ZONE'           , 'Europe/Paris' );


/**
 * Keys are severities and values are bootstrap classes for table highlights
 *
 * @var  array
 */
$badges = array(
	'severity' => array(
		'debug'  => 'success',
		'info'   => 'success',
		'notice' => '',
		'warn'   => 'warning',
		'error'  => 'danger',
		'crit'   => 'danger',
		'alert'  => 'danger',
		'emerg'  => 'danger',
	),
	'http' => array(
		'1' => 'info',
		'2' => 'success',
		'3' => 'default',
		'4' => 'warning',
		'5' => 'danger',
	),
);


/**
 * Logs settings
 *
 * @var  array
 */
$files = array();



